[profile.default]
# Tests are marked as slow if they take more than 1 minute, terminated after 10 minutes
slow-timeout = { period = "1m", terminate-after = 20 }
# Global timeout for the entire test run. Test runs will be terminated if they take longer than this timeout.
global-timeout = "1h"
# Do not stop the test run on the first failure, but continue to run all tests.
fail-fast = false

[profile.default.junit]
# Save junit report to the project root.
path = "test-results.xml"

[[profile.default.overrides]]
# Tests in `prover.rs` rely on prover (CPU or GPU). CPU prover can take >10m to prove one batch, so we give these tests
# a longer timeout.
filter = 'binary(prover)'
slow-timeout = { period = "15m", terminate-after = 3 }

# Skip slow external node tests in coverage profile
# TODO: investigate why this test gets stuck in coverage runs
# by producing 550s proving computations in coverage mode
[profile.coverage]
default-filter = 'not test(does_not_get_stuck)'
