#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 /absolute/path/to/zksync-os" >&2
  exit 1
fi

ZKSYNC_OS_PATH="$1"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PATCH_FILE="${SCRIPT_DIR}/patches/zksync-os-syscoin.patch"

if ! git -C "${ZKSYNC_OS_PATH}" rev-parse --show-toplevel >/dev/null 2>&1; then
  echo "error: ${ZKSYNC_OS_PATH} is not a git repository root" >&2
  exit 1
fi

if [[ ! -f "${PATCH_FILE}" ]]; then
  echo "error: patch file not found: ${PATCH_FILE}" >&2
  exit 1
fi

has_text() {
  local needle="$1"
  local file="$2"
  if command -v rg >/dev/null 2>&1; then
    rg -q --fixed-strings "$needle" "$file"
  else
    grep -q --fixed-strings "$needle" "$file"
  fi
}

syscoin_edge_da_commit_target_from_env() {
  local target="${SYSCOIN_EDGE_DA_COMMIT_TARGET:-${ZKSYNC_OS_SYSCOIN_EDGE_DA_COMMIT_TARGET:-}}"
  [ -n "${target}" ] || {
    echo "error: set SYSCOIN_EDGE_DA_COMMIT_TARGET to the deployed Gateway validator_timelock_addr" >&2
    exit 1
  }
  TARGET="${target}" python3 - <<'PY'
import os

addr = os.environ["TARGET"].strip().lower()
if not addr.startswith("0x") or len(addr) != 42:
    raise SystemExit("SYSCOIN_EDGE_DA_COMMIT_TARGET must be a 20-byte hex address")
if any(c not in "0123456789abcdef" for c in addr[2:]):
    raise SystemExit("SYSCOIN_EDGE_DA_COMMIT_TARGET must be a 20-byte hex address")
if addr == "0x" + "0" * 40:
    raise SystemExit("SYSCOIN_EDGE_DA_COMMIT_TARGET must be nonzero")
print(addr)
PY
}

syscoin_expected_fee_recipient_from_env() {
  local target="${SYSCOIN_EXPECTED_FEE_RECIPIENT:-${ZKSYNC_OS_SYSCOIN_EXPECTED_FEE_RECIPIENT:-}}"
  if [ -z "${target}" ]; then
    echo "0x0000000000000000000000000000000000000000"
    return 0
  fi
  TARGET="${target}" python3 - <<'PY'
import os

addr = os.environ["TARGET"].strip().lower()
if not addr.startswith("0x") or len(addr) != 42:
    raise SystemExit("SYSCOIN_EXPECTED_FEE_RECIPIENT must be a 20-byte hex address")
if any(c not in "0123456789abcdef" for c in addr[2:]):
    raise SystemExit("SYSCOIN_EXPECTED_FEE_RECIPIENT must be a 20-byte hex address")
if addr == "0x" + "0" * 40:
    raise SystemExit("SYSCOIN_EXPECTED_FEE_RECIPIENT must be nonzero when set")
print(addr)
PY
}

write_syscoin_edge_da_commit_target() {
  local target expected_fee_recipient
  target="$(syscoin_edge_da_commit_target_from_env)"
  expected_fee_recipient="$(syscoin_expected_fee_recipient_from_env)"
  local out="${ZKSYNC_OS_PATH}/basic_bootloader/src/bootloader/transaction_flow/zk/syscoin_edge_da.rs"
  TARGET="${target}" EXPECTED_FEE_RECIPIENT="${expected_fee_recipient}" OUT="${out}" python3 - <<'PY'
import os
from pathlib import Path

def normalized_hex(env_name: str, *, nonzero: bool) -> str:
    value = os.environ[env_name].strip().lower()
    hex_addr = value[2:] if value.startswith("0x") else value
    if len(hex_addr) != 40 or any(c not in "0123456789abcdef" for c in hex_addr):
        raise SystemExit(f"{env_name} must be a 20-byte lowercase hex address")
    if nonzero and int(hex_addr, 16) == 0:
        raise SystemExit(f"{env_name} must be nonzero")
    return hex_addr

target = normalized_hex("TARGET", nonzero=True)
expected_fee_recipient = normalized_hex("EXPECTED_FEE_RECIPIENT", nonzero=False)
target_bytes = ", ".join(f"0x{target[i:i+2]}" for i in range(0, 40, 2))
expected_bytes = ", ".join(
    f"0x{expected_fee_recipient[i:i+2]}" for i in range(0, 40, 2)
)
path = Path(os.environ["OUT"])
path.write_text(
    "// This file is generated by scripts/apply-zksync-os-syscoin-patch.sh.\n"
    "// SYSCOIN: deployment-specific Gateway targets and fee-recipient policy.\n"
    "use ruint::aliases::B160;\n\n"
    "pub fn syscoin_compact_edge_da_commit_target() -> B160 {\n"
    f"    B160::from_be_bytes([{target_bytes}])\n"
    "}\n\n"
    "pub fn syscoin_expected_fee_recipient() -> B160 {\n"
    f"    B160::from_be_bytes([{expected_bytes}])\n"
    "}\n",
    encoding="utf-8",
)
PY
}

base_patch_applied() {
  has_text "Blob data id advice mismatch" "${ZKSYNC_OS_PATH}/basic_bootloader/src/bootloader/block_flow/zk/post_tx_op/da_commitment_generator/blob_commitment_generator/mod.rs" \
    && has_text "const USIZE_LEN: usize = 32 / size_of::<usize>();" "${ZKSYNC_OS_PATH}/basic_bootloader/src/bootloader/block_flow/zk/post_tx_op/da_commitment_generator/blob_commitment_generator/commitment_and_proof_advice.rs" \
    && has_text "SYSCOIN: Keep the legacy function name/interface, but return blob data id" "${ZKSYNC_OS_PATH}/callable_oracles/src/blob_kzg_commitment/mod.rs" \
    && has_text "pub const ENCODABLE_BYTES_PER_BLOB: usize = 2 * 1024 * 1024;" "${ZKSYNC_OS_PATH}/basic_bootloader/src/bootloader/block_flow/zk/post_tx_op/da_commitment_generator/blob_commitment_generator/mod.rs" \
    && has_text "blobs_advice.push(8);" "${ZKSYNC_OS_PATH}/forward_system/src/run/mod.rs"
}

canonical_upgrade_fix_applied() {
  has_text "canonical_upgrade_tx_hash: Bytes32::ZERO," "${ZKSYNC_OS_PATH}/zk_ee/src/system/metadata/zk_metadata.rs" \
    && has_text "recorded_upgrade_tx_hash" "${ZKSYNC_OS_PATH}/basic_bootloader/src/bootloader/block_flow/zk/post_tx_op/post_tx_op_proving_singleblock_batch.rs" \
    && has_text "canonical upgrade tx hash mismatch" "${ZKSYNC_OS_PATH}/basic_bootloader/src/bootloader/block_flow/zk/post_tx_op/post_tx_op_proving_singleblock_batch.rs" \
    && has_text "pub fn syscoin_compact_edge_da_commit_target() -> B160" "${ZKSYNC_OS_PATH}/basic_bootloader/src/bootloader/transaction_flow/zk/syscoin_edge_da.rs" \
    && has_text "pub fn syscoin_expected_fee_recipient() -> B160" "${ZKSYNC_OS_PATH}/basic_bootloader/src/bootloader/transaction_flow/zk/syscoin_edge_da.rs" \
    && has_text "syscoin_edge_da::syscoin_compact_edge_da_commit_target" "${ZKSYNC_OS_PATH}/basic_bootloader/src/bootloader/transaction_flow/zk/mod.rs" \
    && has_text "apply_syscoin_edge_da_refs_root_for_tx_numbers" "${ZKSYNC_OS_PATH}/zk_ee/src/common_structs/logs_storage.rs"
}

slh_dsa_precompile_applied() {
  has_text "slh_dsa_precompile = [\"evm_interpreter/slh_dsa_precompile\"]" "${ZKSYNC_OS_PATH}/system_hooks/Cargo.toml" \
    && has_text "SLH_DSA_SHA2_128_24_VERIFY_HOOK_ADDRESS_LOW" "${ZKSYNC_OS_PATH}/evm_interpreter/src/precompile_addresses.rs" \
    && has_text "SlhDsaSha212824VerifyImpl" "${ZKSYNC_OS_PATH}/basic_system/src/system_functions/slh_dsa_sha2_128_24_verify.rs" \
    && has_text "system_hooks/slh_dsa_precompile" "${ZKSYNC_OS_PATH}/forward_system/Cargo.toml"
}

if base_patch_applied && canonical_upgrade_fix_applied && slh_dsa_precompile_applied; then
  write_syscoin_edge_da_commit_target
  echo "zksync-os Syscoin patch appears already applied; skipping." >&2
  exit 0
fi

if base_patch_applied && { ! canonical_upgrade_fix_applied || ! slh_dsa_precompile_applied; }; then
  echo "error: detected an older partially applied Syscoin patch in ${ZKSYNC_OS_PATH}." >&2
  echo "Please start from a clean upstream checkout/tag before applying the updated patch." >&2
  exit 1
fi

echo "Checking patch applicability..." >&2
git -C "${ZKSYNC_OS_PATH}" apply --check --recount "${PATCH_FILE}"

echo "Applying zksync-os Syscoin patch..." >&2
git -C "${ZKSYNC_OS_PATH}" apply --recount "${PATCH_FILE}"
write_syscoin_edge_da_commit_target

echo "Patch applied successfully." >&2
