#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 /absolute/path/to/zksync-os" >&2
  exit 1
fi

ZKSYNC_OS_PATH="$1"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PATCH_FILE="${SCRIPT_DIR}/patches/zksync-os-syscoin.patch"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
: "${PROTOCOL_VERSION:=v31.0}"

if ! git -C "${ZKSYNC_OS_PATH}" rev-parse --show-toplevel >/dev/null 2>&1; then
  echo "error: ${ZKSYNC_OS_PATH} is not a git repository root" >&2
  exit 1
fi

if [[ ! -f "${PATCH_FILE}" ]]; then
  echo "error: patch file not found: ${PATCH_FILE}" >&2
  exit 1
fi

has_text() {
  local needle="$1"
  local file="$2"
  if command -v rg >/dev/null 2>&1; then
    rg -q --fixed-strings "$needle" "$file"
  else
    grep -q --fixed-strings "$needle" "$file"
  fi
}

syscoin_edge_da_commit_target_from_versions() {
  local vf="${REPO_ROOT}/local-chains/${PROTOCOL_VERSION}/versions.yaml"
  [ -f "${vf}" ] || {
    echo "error: missing versions file: ${vf}" >&2
    exit 1
  }
  VERSIONS_YAML="${vf}" python3 - <<'PY'
import os, re

text = open(os.environ["VERSIONS_YAML"], "r", encoding="utf-8").read()
m = re.search(
    r"(?m)^\s*syscoin_edge_da_commit_target:\s*['\"]?(0x[0-9a-fA-F]{40})['\"]?\s*$",
    text,
)
if not m:
    raise SystemExit("syscoin_edge_da_commit_target not found in versions.yaml")
addr = m.group(1).lower()
if addr == "0x" + "0" * 40:
    raise SystemExit("syscoin_edge_da_commit_target must be nonzero")
print(addr)
PY
}

write_syscoin_edge_da_commit_target() {
  local target var_name var_value var_value_lc
  target="$(syscoin_edge_da_commit_target_from_versions)"
  for var_name in SYSCOIN_EDGE_DA_COMMIT_TARGET ZKSYNC_OS_SYSCOIN_EDGE_DA_COMMIT_TARGET; do
    var_value="${!var_name:-}"
    if [ -n "${var_value}" ]; then
      var_value_lc="$(printf '%s' "${var_value}" | tr '[:upper:]' '[:lower:]')"
      if [ "${var_value_lc}" != "${target}" ]; then
        echo "error: ${var_name}=${var_value} does not match versions.yaml syscoin_edge_da_commit_target=${target}" >&2
        exit 1
      fi
    fi
  done
  local out="${ZKSYNC_OS_PATH}/basic_bootloader/src/bootloader/transaction_flow/zk/syscoin_edge_da.rs"
  TARGET="${target}" OUT="${out}" python3 - <<'PY'
import os
from pathlib import Path

target = os.environ["TARGET"].strip().lower()
if target.startswith("0x"):
    hex_addr = target[2:]
else:
    hex_addr = target
if len(hex_addr) != 40 or any(c not in "0123456789abcdef" for c in hex_addr):
    raise SystemExit("SYSCOIN edge DA commit target must be a 20-byte lowercase hex address")
if int(hex_addr, 16) == 0:
    raise SystemExit("SYSCOIN edge DA commit target must be nonzero")

bytes_literal = ", ".join(f"0x{hex_addr[i:i+2]}" for i in range(0, 40, 2))
path = Path(os.environ["OUT"])
path.write_text(
    "// This file is generated by scripts/apply-zksync-os-syscoin-patch.sh.\n"
    "// SYSCOIN: protocol-versioned Gateway ValidatorTimelock commit target.\n"
    "use ruint::aliases::B160;\n\n"
    "pub fn syscoin_compact_edge_da_commit_target() -> B160 {\n"
    f"    B160::from_be_bytes([{bytes_literal}])\n"
    "}\n",
    encoding="utf-8",
)
PY
}

base_patch_applied() {
  has_text "Blob data id advice mismatch" "${ZKSYNC_OS_PATH}/basic_bootloader/src/bootloader/block_flow/zk/post_tx_op/da_commitment_generator/blob_commitment_generator/mod.rs" \
    && has_text "const USIZE_LEN: usize = 32 / size_of::<usize>();" "${ZKSYNC_OS_PATH}/basic_bootloader/src/bootloader/block_flow/zk/post_tx_op/da_commitment_generator/blob_commitment_generator/commitment_and_proof_advice.rs" \
    && has_text "SYSCOIN: Keep the legacy function name/interface, but return blob data id" "${ZKSYNC_OS_PATH}/callable_oracles/src/blob_kzg_commitment/mod.rs" \
    && has_text "pub const ENCODABLE_BYTES_PER_BLOB: usize = 2 * 1024 * 1024;" "${ZKSYNC_OS_PATH}/basic_bootloader/src/bootloader/block_flow/zk/post_tx_op/da_commitment_generator/blob_commitment_generator/mod.rs" \
    && has_text "blobs_advice.push(8);" "${ZKSYNC_OS_PATH}/forward_system/src/run/mod.rs"
}

canonical_upgrade_fix_applied() {
  has_text "canonical_upgrade_tx_hash: Bytes32::ZERO," "${ZKSYNC_OS_PATH}/zk_ee/src/system/metadata/zk_metadata.rs" \
    && has_text "recorded_upgrade_tx_hash" "${ZKSYNC_OS_PATH}/basic_bootloader/src/bootloader/block_flow/zk/post_tx_op/post_tx_op_proving_singleblock_batch.rs" \
    && has_text "canonical upgrade tx hash mismatch" "${ZKSYNC_OS_PATH}/basic_bootloader/src/bootloader/block_flow/zk/post_tx_op/post_tx_op_proving_singleblock_batch.rs" \
    && has_text "syscoin_compact_edge_da_commit_target" "${ZKSYNC_OS_PATH}/zk_ee/src/system/metadata/zk_metadata.rs" \
    && has_text "syscoin_edge_da::syscoin_compact_edge_da_commit_target" "${ZKSYNC_OS_PATH}/basic_bootloader/src/bootloader/transaction_flow/zk/mod.rs" \
    && has_text "apply_syscoin_edge_da_refs_root_for_tx_numbers" "${ZKSYNC_OS_PATH}/zk_ee/src/common_structs/logs_storage.rs"
}

slh_dsa_precompile_applied() {
  has_text "slh_dsa_precompile = [\"evm_interpreter/slh_dsa_precompile\"]" "${ZKSYNC_OS_PATH}/system_hooks/Cargo.toml" \
    && has_text "SLH_DSA_SHA2_128_24_VERIFY_HOOK_ADDRESS_LOW" "${ZKSYNC_OS_PATH}/evm_interpreter/src/precompile_addresses.rs" \
    && has_text "SlhDsaSha212824VerifyImpl" "${ZKSYNC_OS_PATH}/basic_system/src/system_functions/slh_dsa_sha2_128_24_verify.rs" \
    && has_text "system_hooks/slh_dsa_precompile" "${ZKSYNC_OS_PATH}/forward_system/Cargo.toml"
}

if base_patch_applied && canonical_upgrade_fix_applied && slh_dsa_precompile_applied; then
  write_syscoin_edge_da_commit_target
  echo "zksync-os Syscoin patch appears already applied; skipping." >&2
  exit 0
fi

if base_patch_applied && { ! canonical_upgrade_fix_applied || ! slh_dsa_precompile_applied; }; then
  echo "error: detected an older partially applied Syscoin patch in ${ZKSYNC_OS_PATH}." >&2
  echo "Please start from a clean upstream checkout/tag before applying the updated patch." >&2
  exit 1
fi

echo "Checking patch applicability..." >&2
git -C "${ZKSYNC_OS_PATH}" apply --check --recount "${PATCH_FILE}"

echo "Applying zksync-os Syscoin patch..." >&2
git -C "${ZKSYNC_OS_PATH}" apply --recount "${PATCH_FILE}"
write_syscoin_edge_da_commit_target

echo "Patch applied successfully." >&2
