[package]
name = "zksync_os_native_pig"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zksync_os_batch_types.workspace = true
zksync_os_interface.workspace = true
zksync_os_merkle_tree.workspace = true
zksync_os_storage_api.workspace = true
zksync_os_types.workspace = true

zk_os_forward_system_0_4_0.workspace = true
zk_os_basic_system_0_4_0.workspace = true
zk_ee_0_4_0.workspace = true

alloy.workspace = true
anyhow.workspace = true
tracing.workspace = true
vise.workspace = true
